#on: [push]
on:
  label:
    types: [created]

jobs:
  hello_world_job:
    if: github.event.label.name == 'docs'
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
         git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
